server:
  port: 8082
spring:
  application:
    name: Notification-Api
  datasource:
    pg:
      url: jdbc:postgresql://192.168.18.31:5431/bora_jogar
      username: postgres
      password: example
      driverClassName: org.postgresql.Driver
    mg:
      host: 192.168.18.31
      port: 27017
      database: bora-jogar
      username:
      password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        cache:
          ehcache:
            missing_cache_strategy: create
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_query_cache: true
          use_second_level_cache: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: America/Sao_Paulo
          batch_size: 100
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: America/Sao_Paulo
  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    port: 2525
    username: ad196219511361
    password: 566e6de8c26f75
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false
    protocol: smtp
    test-connection: false
  rabbitmq:
    host: 192.168.18.31
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: false
logging:
  level:
    com.br.unifacef.notification: DEBUG
    org.springframework: ERROR
app:
  mailFrom: bora_jogar@mail.com